import { supabase } from '../lib/supabase';

export const seedArticles = async () => {
  const articles = [
    {
      title_pt: 'Brasil e Rússia Ampliam Acordo de Cooperação Tecnológica',
      title_ru: 'Бразилия и Россия расширяют соглашение о технологическом сотрудничестве',
      title_en: 'Brazil and Russia Expand Technological Cooperation Agreement',
      slug: 'brasil-russia-cooperacao-tecnologica-2025',
      excerpt_pt: 'Novo acordo prevê investimentos de US$ 500 milhões em projetos de inovação e desenvolvimento tecnológico entre os dois países.',
      excerpt_ru: 'Новое соглашение предусматривает инвестиции в размере 500 миллионов долларов США в инновационные и технологические проекты между двумя странами.',
      excerpt_en: 'New agreement provides for investments of US$ 500 million in innovation and technological development projects between the two countries.',
      content_pt: 'O Brasil e a Rússia assinaram um acordo histórico que amplia a cooperação tecnológica entre os dois países. O acordo prevê investimentos significativos em áreas como inteligência artificial, tecnologia espacial e desenvolvimento de software. As empresas brasileiras terão acesso facilitado ao mercado russo de tecnologia, enquanto empresas russas poderão estabelecer centros de pesquisa no Brasil.',
      content_ru: 'Бразилия и Россия подписали историческое соглашение, которое расширяет технологическое сотрудничество между двумя странами. Соглашение предусматривает значительные инвестиции в такие области, как искусственный интеллект, космические технологии и разработка программного обеспечения.',
      content_en: 'Brazil and Russia have signed a historic agreement that expands technological cooperation between the two countries. The agreement provides for significant investments in areas such as artificial intelligence, space technology and software development.',
      category: 'Tecnologia',
      author: 'Maria Petrova',
      image_url: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '8 min',
      is_featured: true,
      is_members_only: false,
      published_at: new Date().toISOString()
    },
    {
      title_pt: 'Exportações Brasileiras para Rússia Crescem 45% no Último Trimestre',
      title_ru: 'Экспорт Бразилии в Россию вырос на 45% в последнем квартале',
      title_en: 'Brazilian Exports to Russia Grow 45% in Last Quarter',
      slug: 'exportacoes-brasil-russia-crescimento-2025',
      excerpt_pt: 'Setor agrícola lidera crescimento com aumento nas exportações de soja, café e carne bovina.',
      excerpt_ru: 'Сельскохозяйственный сектор лидирует в росте с увеличением экспорта сои, кофе и говядины.',
      excerpt_en: 'Agricultural sector leads growth with increased exports of soybeans, coffee and beef.',
      content_pt: 'As exportações brasileiras para a Rússia registraram um crescimento expressivo de 45% no último trimestre, impulsionadas principalmente pelo setor agrícola. A soja brasileira consolidou sua posição como principal produto de exportação, seguida por café premium e carne bovina de alta qualidade.',
      content_ru: 'Экспорт Бразилии в Россию показал значительный рост на 45% в последнем квартале, в основном за счет сельскохозяйственного сектора.',
      content_en: 'Brazilian exports to Russia recorded significant growth of 45% in the last quarter, driven mainly by the agricultural sector.',
      category: 'Comércio',
      author: 'João Silva',
      image_url: 'https://images.pexels.com/photos/534216/pexels-photo-534216.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '6 min',
      is_featured: true,
      is_members_only: false,
      published_at: new Date(Date.now() - 86400000).toISOString()
    },
    {
      title_pt: 'Missão Comercial Brasileira Visita Moscou em Busca de Novos Negócios',
      title_ru: 'Бразильская торговая миссия посещает Москву в поисках новых возможностей',
      title_en: 'Brazilian Trade Mission Visits Moscow Seeking New Business',
      slug: 'missao-comercial-moscou-2025',
      excerpt_pt: 'Delegação de 50 empresários brasileiros participa de rodadas de negócios na capital russa.',
      excerpt_ru: 'Делегация из 50 бразильских бизнесменов участвует в деловых переговорах в российской столице.',
      excerpt_en: 'Delegation of 50 Brazilian entrepreneurs participates in business rounds in the Russian capital.',
      content_pt: 'Uma delegação de 50 empresários brasileiros está em Moscou participando de uma série de rodadas de negócios organizadas pela Câmara de Comércio Brasil-Rússia. O objetivo é estabelecer novas parcerias comerciais e explorar oportunidades nos setores de tecnologia, construção civil e energia renovável.',
      content_ru: 'Делегация из 50 бразильских предпринимателей находится в Москве, участвуя в серии деловых переговоров, организованных Бразильско-Российской торговой палатой.',
      content_en: 'A delegation of 50 Brazilian entrepreneurs is in Moscow participating in a series of business rounds organized by the Brazil-Russia Chamber of Commerce.',
      category: 'Comércio',
      author: 'Ana Costa',
      image_url: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '7 min',
      is_featured: true,
      is_members_only: false,
      published_at: new Date(Date.now() - 172800000).toISOString()
    },
    {
      title_pt: 'Festival de Cultura Russa no Brasil Atrai Mais de 50 Mil Visitantes',
      title_ru: 'Фестиваль русской культуры в Бразилии привлекает более 50 тысяч посетителей',
      title_en: 'Russian Culture Festival in Brazil Attracts Over 50,000 Visitors',
      slug: 'festival-cultura-russa-brasil-2025',
      excerpt_pt: 'Evento em São Paulo apresenta gastronomia, música, dança e arte russa.',
      excerpt_ru: 'Мероприятие в Сан-Паулу представляет русскую кухню, музыку, танцы и искусство.',
      excerpt_en: 'Event in São Paulo features Russian gastronomy, music, dance and art.',
      content_pt: 'O Festival de Cultura Russa realizado em São Paulo foi um grande sucesso, atraindo mais de 50 mil visitantes durante três dias de evento. O festival contou com apresentações de ballet, música clássica, exposições de arte e uma ampla variedade de pratos típicos da culinária russa.',
      content_ru: 'Фестиваль русской культуры, проведенный в Сан-Паулу, имел большой успех, привлекая более 50 тысяч посетителей в течение трех дней мероприятия.',
      content_en: 'The Russian Culture Festival held in São Paulo was a great success, attracting over 50,000 visitors during three days of the event.',
      category: 'Cultura',
      author: 'Svetlana Ivanova',
      image_url: 'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '5 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 259200000).toISOString()
    },
    {
      title_pt: 'Setor de Turismo Entre Brasil e Rússia Apresenta Crescimento Recorde',
      title_ru: 'Туристический сектор между Бразилией и Россией показывает рекордный рост',
      title_en: 'Tourism Sector Between Brazil and Russia Shows Record Growth',
      slug: 'turismo-brasil-russia-crescimento-2025',
      excerpt_pt: 'Número de turistas russos no Brasil aumenta 60% em relação ao ano anterior.',
      excerpt_ru: 'Число российских туристов в Бразилии увеличилось на 60% по сравнению с прошлым годом.',
      excerpt_en: 'Number of Russian tourists in Brazil increases 60% compared to previous year.',
      content_pt: 'O setor de turismo entre Brasil e Rússia está experimentando um crescimento sem precedentes. O número de turistas russos visitando o Brasil cresceu 60% em relação ao ano anterior, com destaque para destinos como Rio de Janeiro, Foz do Iguaçu e Fernando de Noronha.',
      content_ru: 'Туристический сектор между Бразилией и Россией переживает беспрецедентный рост.',
      content_en: 'The tourism sector between Brazil and Russia is experiencing unprecedented growth.',
      category: 'Turismo',
      author: 'Carlos Mendes',
      image_url: 'https://images.pexels.com/photos/2846217/pexels-photo-2846217.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '6 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 345600000).toISOString()
    },
    {
      title_pt: 'Startups Brasileiras Buscam Investimento em Fundo Russo de Inovação',
      title_ru: 'Бразильские стартапы ищут инвестиции в российском инновационном фонде',
      title_en: 'Brazilian Startups Seek Investment in Russian Innovation Fund',
      slug: 'startups-brasileiras-fundo-russo-2025',
      excerpt_pt: 'Programa de aceleração conecta empreendedores brasileiros com investidores russos.',
      excerpt_ru: 'Программа ускорения связывает бразильских предпринимателей с российскими инвесторами.',
      excerpt_en: 'Acceleration program connects Brazilian entrepreneurs with Russian investors.',
      content_pt: 'Um novo programa de aceleração está conectando startups brasileiras com o Fundo Russo de Inovação. A iniciativa visa promover a cooperação tecnológica e facilitar o acesso a capital para empresas em estágio inicial nos setores de fintech, healthtech e agritech.',
      content_ru: 'Новая программа ускорения связывает бразильские стартапы с Российским инновационным фондом.',
      content_en: 'A new acceleration program is connecting Brazilian startups with the Russian Innovation Fund.',
      category: 'Inovação',
      author: 'Pedro Oliveira',
      image_url: 'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '7 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 432000000).toISOString()
    },
    {
      title_pt: 'Indústria Automotiva: Parceria Brasil-Rússia Desenvolve Veículos Elétricos',
      title_ru: 'Автомобильная промышленность: партнерство Бразилии и России разрабатывает электромобили',
      title_en: 'Automotive Industry: Brazil-Russia Partnership Develops Electric Vehicles',
      slug: 'industria-automotiva-veiculos-eletricos-2025',
      excerpt_pt: 'Joint venture planeja produção de 100 mil veículos elétricos até 2027.',
      excerpt_ru: 'Совместное предприятие планирует производство 100 тысяч электромобилей к 2027 году.',
      excerpt_en: 'Joint venture plans production of 100,000 electric vehicles by 2027.',
      content_pt: 'Uma joint venture entre empresas brasileiras e russas anunciou planos ambiciosos para desenvolver e produzir veículos elétricos. O projeto prevê a construção de uma fábrica no Brasil com capacidade para produzir 100 mil unidades anuais até 2027.',
      content_ru: 'Совместное предприятие между бразильскими и российскими компаниями объявило амбициозные планы по разработке и производству электромобилей.',
      content_en: 'A joint venture between Brazilian and Russian companies has announced ambitious plans to develop and produce electric vehicles.',
      category: 'Indústria',
      author: 'Marina Sokolova',
      image_url: 'https://images.pexels.com/photos/110844/pexels-photo-110844.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '8 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 518400000).toISOString()
    },
    {
      title_pt: 'Acordo de Investimento em Energia Renovável Soma R$ 2 Bilhões',
      title_ru: 'Соглашение об инвестициях в возобновляемую энергетику составляет 2 миллиарда реалов',
      title_en: 'Renewable Energy Investment Agreement Totals R$ 2 Billion',
      slug: 'investimento-energia-renovavel-2025',
      excerpt_pt: 'Projetos de energia solar e eólica receberão investimentos russos no Nordeste brasileiro.',
      excerpt_ru: 'Проекты солнечной и ветровой энергии получат российские инвестиции на северо-востоке Бразилии.',
      excerpt_en: 'Solar and wind energy projects will receive Russian investments in Northeast Brazil.',
      content_pt: 'Brasil e Rússia firmaram acordo para investimentos de R$ 2 bilhões em projetos de energia renovável. Os recursos serão destinados à construção de parques solares e eólicos na região Nordeste do Brasil, aproveitando o alto potencial energético da região.',
      content_ru: 'Бразилия и Россия подписали соглашение об инвестициях в размере 2 миллиардов реалов в проекты возобновляемой энергетики.',
      content_en: 'Brazil and Russia have signed an agreement for investments of R$ 2 billion in renewable energy projects.',
      category: 'Energia',
      author: 'Roberto Santos',
      image_url: 'https://images.pexels.com/photos/433308/pexels-photo-433308.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '9 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 604800000).toISOString()
    },
    {
      title_pt: 'Intercâmbio Acadêmico: 500 Bolsas de Estudo Oferecidas',
      title_ru: 'Академический обмен: предлагается 500 стипендий',
      title_en: 'Academic Exchange: 500 Scholarships Offered',
      slug: 'intercambio-academico-bolsas-2025',
      excerpt_pt: 'Programa de intercâmbio oferece oportunidades para estudantes brasileiros em universidades russas.',
      excerpt_ru: 'Программа обмена предлагает возможности для бразильских студентов в российских университетах.',
      excerpt_en: 'Exchange program offers opportunities for Brazilian students at Russian universities.',
      content_pt: 'Foi lançado um novo programa de intercâmbio acadêmico que oferece 500 bolsas de estudo integrais para estudantes brasileiros em universidades russas. As bolsas cobrem cursos de graduação e pós-graduação nas áreas de engenharia, ciências exatas e medicina.',
      content_ru: 'Запущена новая программа академического обмена, которая предлагает 500 полных стипендий для бразильских студентов в российских университетах.',
      content_en: 'A new academic exchange program has been launched offering 500 full scholarships for Brazilian students at Russian universities.',
      category: 'Educação',
      author: 'Elena Kuznetsova',
      image_url: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '6 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 691200000).toISOString()
    },
    {
      title_pt: 'Setor Farmacêutico: Acordo para Produção de Medicamentos no Brasil',
      title_ru: 'Фармацевтический сектор: соглашение о производстве лекарств в Бразилии',
      title_en: 'Pharmaceutical Sector: Agreement for Drug Production in Brazil',
      slug: 'setor-farmaceutico-producao-medicamentos-2025',
      excerpt_pt: 'Parceria visa produção local de medicamentos essenciais e redução de custos.',
      excerpt_ru: 'Партнерство направлено на местное производство основных лекарств и снижение затрат.',
      excerpt_en: 'Partnership aims at local production of essential medicines and cost reduction.',
      content_pt: 'Brasil e Rússia assinaram acordo para produção local de medicamentos essenciais. A parceria inclui transferência de tecnologia e instalação de plantas farmacêuticas no Brasil, com foco em medicamentos para tratamento de doenças crônicas.',
      content_ru: 'Бразилия и Россия подписали соглашение о местном производстве основных лекарств.',
      content_en: 'Brazil and Russia have signed an agreement for local production of essential medicines.',
      category: 'Saúde',
      author: 'Tatiana Volkov',
      image_url: 'https://images.pexels.com/photos/3825527/pexels-photo-3825527.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '7 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 777600000).toISOString()
    },
    {
      title_pt: 'Agronegócio: Tecnologia Russa Aumenta Produtividade de Culturas Brasileiras',
      title_ru: 'Агробизнес: российские технологии повышают продуктивность бразильских культур',
      title_en: 'Agribusiness: Russian Technology Increases Productivity of Brazilian Crops',
      slug: 'agronegocio-tecnologia-russa-2025',
      excerpt_pt: 'Sistemas de irrigação inteligente desenvolvidos na Rússia chegam ao Brasil.',
      excerpt_ru: 'Интеллектуальные системы орошения, разработанные в России, прибывают в Бразилию.',
      excerpt_en: 'Smart irrigation systems developed in Russia arrive in Brazil.',
      content_pt: 'Agricultores brasileiros estão adotando tecnologia russa de irrigação inteligente que promete aumentar a produtividade em até 30%. O sistema utiliza sensores avançados e inteligência artificial para otimizar o uso de água e fertilizantes.',
      content_ru: 'Бразильские фермеры внедряют российскую технологию интеллектуального орошения, которая обещает увеличить производительность до 30%.',
      content_en: 'Brazilian farmers are adopting Russian smart irrigation technology that promises to increase productivity by up to 30%.',
      category: 'Agronegócio',
      author: 'Dmitri Ivanov',
      image_url: 'https://images.pexels.com/photos/2252584/pexels-photo-2252584.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '8 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 864000000).toISOString()
    },
    {
      title_pt: 'Construção Civil: Empresas Russas Investem em Projetos de Infraestrutura',
      title_ru: 'Строительство: российские компании инвестируют в инфраструктурные проекты',
      title_en: 'Construction: Russian Companies Invest in Infrastructure Projects',
      slug: 'construcao-civil-infraestrutura-2025',
      excerpt_pt: 'Investimento de US$ 800 milhões em rodovias e portos brasileiros.',
      excerpt_ru: 'Инвестиции в размере 800 миллионов долларов США в бразильские дороги и порты.',
      excerpt_en: 'Investment of US$ 800 million in Brazilian highways and ports.',
      content_pt: 'Empresas russas de construção civil anunciaram investimentos de US$ 800 milhões em projetos de infraestrutura no Brasil. Os recursos serão aplicados na modernização de rodovias e ampliação de capacidade portuária.',
      content_ru: 'Российские строительные компании объявили об инвестициях в размере 800 миллионов долларов США в инфраструктурные проекты в Бразилии.',
      content_en: 'Russian construction companies have announced investments of US$ 800 million in infrastructure projects in Brazil.',
      category: 'Infraestrutura',
      author: 'Alexei Petrov',
      image_url: 'https://images.pexels.com/photos/210607/pexels-photo-210607.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '7 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 950400000).toISOString()
    },
    {
      title_pt: 'Cooperação Espacial: Brasil e Rússia Planejam Missão Conjunta',
      title_ru: 'Космическое сотрудничество: Бразилия и Россия планируют совместную миссию',
      title_en: 'Space Cooperation: Brazil and Russia Plan Joint Mission',
      slug: 'cooperacao-espacial-missao-conjunta-2025',
      excerpt_pt: 'Agências espaciais dos dois países desenvolvem satélite de observação ambiental.',
      excerpt_ru: 'Космические агентства двух стран разрабатывают спутник экологического мониторинга.',
      excerpt_en: 'Space agencies of both countries develop environmental observation satellite.',
      content_pt: 'As agências espaciais do Brasil e da Rússia estão desenvolvendo um satélite conjunto para monitoramento ambiental da Amazônia. O projeto representa um marco importante na cooperação científica bilateral.',
      content_ru: 'Космические агентства Бразилии и России разрабатывают совместный спутник для экологического мониторинга Амазонии.',
      content_en: 'The space agencies of Brazil and Russia are developing a joint satellite for environmental monitoring of the Amazon.',
      category: 'Ciência',
      author: 'Natalia Romanova',
      image_url: 'https://images.pexels.com/photos/41006/satellite-moon-space-research-41006.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '9 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 1036800000).toISOString()
    },
    {
      title_pt: 'Setor de Mineração: Joint Venture para Exploração Sustentável',
      title_ru: 'Горнодобывающий сектор: совместное предприятие для устойчивой добычи',
      title_en: 'Mining Sector: Joint Venture for Sustainable Exploration',
      slug: 'setor-mineracao-exploracao-sustentavel-2025',
      excerpt_pt: 'Parceria foca em práticas sustentáveis de mineração com tecnologia avançada.',
      excerpt_ru: 'Партнерство сосредоточено на устойчивых методах добычи с передовыми технологиями.',
      excerpt_en: 'Partnership focuses on sustainable mining practices with advanced technology.',
      content_pt: 'Uma joint venture entre empresas brasileiras e russas do setor de mineração está implementando tecnologias inovadoras para tornar a exploração mineral mais sustentável. O projeto piloto está sendo desenvolvido em Minas Gerais.',
      content_ru: 'Совместное предприятие между бразильскими и российскими компаниями горнодобывающего сектора внедряет инновационные технологии для более устойчивой добычи полезных ископаемых.',
      content_en: 'A joint venture between Brazilian and Russian mining companies is implementing innovative technologies to make mineral exploration more sustainable.',
      category: 'Mineração',
      author: 'Igor Sokolov',
      image_url: 'https://images.pexels.com/photos/1108572/pexels-photo-1108572.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '8 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 1123200000).toISOString()
    },
    {
      title_pt: 'Fintechs Brasileiras e Russas Criam Plataforma de Pagamentos Bilateral',
      title_ru: 'Бразильские и российские финтех-компании создают платформу двусторонних платежей',
      title_en: 'Brazilian and Russian Fintechs Create Bilateral Payment Platform',
      slug: 'fintechs-plataforma-pagamentos-2025',
      excerpt_pt: 'Nova solução facilita transações comerciais entre empresas dos dois países.',
      excerpt_ru: 'Новое решение облегчает коммерческие транзакции между компаниями двух стран.',
      excerpt_en: 'New solution facilitates commercial transactions between companies from both countries.',
      content_pt: 'Fintechs do Brasil e da Rússia lançaram uma plataforma inovadora de pagamentos que facilita transações comerciais bilaterais. A solução reduz custos e o tempo de processamento de pagamentos internacionais.',
      content_ru: 'Финтех-компании из Бразилии и России запустили инновационную платежную платформу, которая облегчает двусторонние коммерческие транзакции.',
      content_en: 'Fintechs from Brazil and Russia have launched an innovative payment platform that facilitates bilateral commercial transactions.',
      category: 'Fintech',
      author: 'Olga Mikhailova',
      image_url: 'https://images.pexels.com/photos/259027/pexels-photo-259027.jpeg?auto=compress&cs=tinysrgb&w=1200',
      read_time: '6 min',
      is_featured: false,
      is_members_only: false,
      published_at: new Date(Date.now() - 1209600000).toISOString()
    }
  ];

  const { data, error } = await supabase
    .from('articles')
    .insert(articles)
    .select();

  if (error) {
    console.error('Error inserting articles:', error);
    return { success: false, error };
  }

  return { success: true, data };
};

export const seedEvents = async () => {
  const events = [
    {
      title_pt: 'Webinar: Oportunidades de Negócio no Mercado Russo',
      title_ru: 'Вебинар: Деловые возможности на российском рынке',
      title_en: 'Webinar: Business Opportunities in the Russian Market',
      description_pt: 'Especialistas apresentam as principais oportunidades de negócio no mercado russo, incluindo setores em crescimento e estratégias de entrada no mercado.',
      description_ru: 'Эксперты представляют основные деловые возможности на российском рынке, включая растущие секторы и стратегии входа на рынок.',
      description_en: 'Experts present the main business opportunities in the Russian market, including growing sectors and market entry strategies.',
      location: 'Online',
      event_date: new Date(Date.now() + 604800000).toISOString(),
      end_date: new Date(Date.now() + 608400000).toISOString(),
      image_url: 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=1200',
      is_paid: false,
      price: null,
      max_attendees: 500,
      is_members_only: false
    },
    {
      title_pt: 'Missão Comercial a São Petersburgo',
      title_ru: 'Торговая миссия в Санкт-Петербург',
      title_en: 'Trade Mission to Saint Petersburg',
      description_pt: 'Missão comercial com agenda de reuniões B2B, visitas técnicas e networking em São Petersburgo.',
      description_ru: 'Торговая миссия с повесткой встреч B2B, технических визитов и нетворкинга в Санкт-Петербурге.',
      description_en: 'Trade mission with B2B meetings agenda, technical visits and networking in Saint Petersburg.',
      location: 'São Petersburgo, Rússia',
      event_date: new Date(Date.now() + 1814400000).toISOString(),
      end_date: new Date(Date.now() + 2073600000).toISOString(),
      image_url: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=1200',
      is_paid: true,
      price: 4500,
      max_attendees: 30,
      is_members_only: true
    },
    {
      title_pt: 'Feira de Tecnologia e Inovação Brasil-Rússia',
      title_ru: 'Выставка технологий и инноваций Бразилия-Россия',
      title_en: 'Brazil-Russia Technology and Innovation Fair',
      description_pt: 'Grande feira com exposição de tecnologias, palestras e oportunidades de networking entre empresas brasileiras e russas.',
      description_ru: 'Крупная выставка с демонстрацией технологий, лекциями и возможностями для нетворкинга между бразильскими и российскими компаниями.',
      description_en: 'Large fair with technology exhibition, lectures and networking opportunities between Brazilian and Russian companies.',
      location: 'Centro de Convenções Frei Caneca, São Paulo',
      event_date: new Date(Date.now() + 2592000000).toISOString(),
      end_date: new Date(Date.now() + 2678400000).toISOString(),
      image_url: 'https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=1200',
      is_paid: true,
      price: 150,
      max_attendees: 1000,
      is_members_only: false
    },
    {
      title_pt: 'Workshop: Como Exportar para a Rússia',
      title_ru: 'Семинар: Как экспортировать в Россию',
      title_en: 'Workshop: How to Export to Russia',
      description_pt: 'Workshop prático sobre documentação, logística e aspectos legais da exportação para o mercado russo.',
      description_ru: 'Практический семинар по документации, логистике и правовым аспектам экспорта на российский рынок.',
      description_en: 'Practical workshop on documentation, logistics and legal aspects of exporting to the Russian market.',
      location: 'Sede da Câmara, São Paulo',
      event_date: new Date(Date.now() + 1209600000).toISOString(),
      end_date: new Date(Date.now() + 1220400000).toISOString(),
      image_url: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=1200',
      is_paid: true,
      price: 250,
      max_attendees: 50,
      is_members_only: false
    },
    {
      title_pt: 'Jantar de Networking com Empresários Russos',
      title_ru: 'Сетевой ужин с российскими предпринимателями',
      title_en: 'Networking Dinner with Russian Entrepreneurs',
      description_pt: 'Evento exclusivo de networking com empresários russos em visita ao Brasil.',
      description_ru: 'Эксклюзивное сетевое мероприятие с российскими предпринимателями, посещающими Бразилию.',
      description_en: 'Exclusive networking event with Russian entrepreneurs visiting Brazil.',
      location: 'Hotel Unique, São Paulo',
      event_date: new Date(Date.now() + 3024000000).toISOString(),
      end_date: new Date(Date.now() + 3038400000).toISOString(),
      image_url: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=1200',
      is_paid: true,
      price: 350,
      max_attendees: 80,
      is_members_only: true
    },
    {
      title_pt: 'Seminário: Investimentos em Energia Renovável',
      title_ru: 'Семинар: Инвестиции в возобновляемую энергетику',
      title_en: 'Seminar: Investments in Renewable Energy',
      description_pt: 'Seminário sobre oportunidades de investimento em projetos de energia renovável entre Brasil e Rússia.',
      description_ru: 'Семинар о возможностях инвестирования в проекты возобновляемой энергетики между Бразилией и Россией.',
      description_en: 'Seminar on investment opportunities in renewable energy projects between Brazil and Russia.',
      location: 'Centro Empresarial, Rio de Janeiro',
      event_date: new Date(Date.now() + 3456000000).toISOString(),
      end_date: new Date(Date.now() + 3470400000).toISOString(),
      image_url: 'https://images.pexels.com/photos/433308/pexels-photo-433308.jpeg?auto=compress&cs=tinysrgb&w=1200',
      is_paid: false,
      price: null,
      max_attendees: 200,
      is_members_only: true
    }
  ];

  const { data, error } = await supabase
    .from('events')
    .insert(events)
    .select();

  if (error) {
    console.error('Error inserting events:', error);
    return { success: false, error };
  }

  return { success: true, data };
};
